#!/usr/bin/python3
import sys
filename = sys.argv[-1]
sys.stdin = open(filename, 'r')
while True:
    try:

        n = int(input())
        if n % 2 == 0:
            print("{}={}*{}".format(n, n//2, 2))
        else:
            div = 3
            flag = False
            while (div*div) <= n:
                if n % div == 0:
                    fir_div = div
                    sec_div = n//div
                    print("{}={}*{}".format(n, max(fir_div,
                                                   sec_div), min(fir_div, sec_div)))
                    flag = True
                    break
                else:
                    div += 2
            if not flag:
                print("{}={}*{}", n, n, 1)

    except EOFError:
        break
